# Generated by Django 3.0.6 on 2020-05-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='mapa',
            field=models.CharField(default='urlmaps', max_length=500),
        ),
    ]
